const funfacts = [
	'Koty to jedne z najbardziej popularnych zwierząt domowych na świecie.',
	'Koty potrafią mruczeć, aby wyrazić zadowolenie lub komunikować się z ludźmi.',
	'Koty mają unikalne odciski łap, podobnie jak ludzie mają unikalne odciski palców.',
	'Koty potrafią być towarzyskie i lubią spędzać czas z innymi kotami.',
	'Koty potrafią być wyczulone na zmiany w harmonii domu i reagować na nie.',
	'Koty potrafią być lojalne i przywiązane do swoich właścicieli.',
	'Koty potrafią być znakomitymi myśliwymi i często polują na gryzonie i ptaki.',
	'Koty potrafią być znakomitymi myśliwymi, ale nie polują z zabijczą intencją.',
	'Koty mają zdolność do zakłócania, na przykład przewracając rzeczy na podłodze.',
	'Koty potrafią odczuwać strach przed wodą i zwykle nie lubią kąpieli.',
	'Koty potrafią rozpoznać innych kotów po zapachu.',
	'Koty mogą komunikować się ze sobą za pomocą mruczenia i miauczenia.',
	'Koty potrafią rozpoznać różnice w tonie głosu i emocjach w głosie swojego właściciela.',
	'Koty potrafią rozpoznać emocje swojego właściciela i reagować na nie.',
	'Koty potrafią rozpoznać różnice w zapachach i często wykazują zainteresowanie nowymi zapachami.',
	'Koty potrafią być bardzo ciekawe i lubią badać nowe rzeczy w otoczeniu.',
	'Koty potrafią rozpoznać głos swojego właściciela.',
	'Koty potrafią komunikować się z innymi kotami za pomocą znaków zapachowych.',
	'Koty potrafią być wrażliwe na zmiany nastroju swojego właściciela.',
	'Koty potrafią być znakomitymi myśliwymi i polują na owady.',
	'Koty potrafią być czułe na zmiany w harmonii domu i reagować na nie.',
	'Koty mają doskonałą zdolność kuwetowego samoczyszczenia.',
	'Koty potrafią wydawać wiele różnych dźwięków, takie jak miauczenie, mruczenie i warczenie.',
	'Koty mogą spać nawet do 16 godzin dziennie.',
	'Koty mogą być wrażliwe na niektóre rośliny, takie jak kocimiętka.',
	'Koty potrafią kuć i gryźć jako forma zabawy.',
	'Koty to jedne z najdłużej domowionych zwierząt w historii ludzkości.',
	'Koty mają doskonały słuch i potrafią usłyszeć dźwięki, których ludzkie ucho nie jest w stanie wychwycić.',
	'Koty to gatunek dziko żyjący, który nie został w pełni udomowiony przez człowieka.',
	'Koty potrafią korzystać z kuwety, co sprawia, że są łatwe do utrzymania w domu.',
	'Koty zawsze są niebieskookie.',
	'Koty nie mogą być tresowane.',
	'Koty mają bardzo rozwinięty zmysł równowagi.',
	'Koty potrafią rozpoznać głos swojego właściciela.',
	'Koty są bardziej samotne niż psy.',
	'Koty są zimnokrwiste, co oznacza, że nie potrzebują ciepła.',
	'Koty lubią drapać różne powierzchnie, aby ostrzyć swoje pazury.',
	'Koty potrafią wyczaić myszy i ptaki w trawie dzięki swojemu doskonałemu wzrokowi.',
	'Koty zawsze chodzą samotnie i nie tworzą grup społecznych.',
	'Koty nie są wrażliwe na wibracje dźwięku.',
	'Koty potrafią osiągnąć prędkość biegu powyżej 30 mil na godzinę.',
	'Koty mają 32 zęby, w tym ostrych kłów.',
	'Koty potrafią wspinać się na drzewa i ogrodzenia.',
	'Koty są znane z tego, że są wybredne w jedzeniu.',
	'Koty mogą cierpieć na alergie, podobnie jak ludzie.',
	'Koty nie potrafią rozpoznać kolorów.',
	'Koty mają doskonały zmysł smaku i potrafią wyczuć nawet niewielkie różnice w jedzeniu.',
	'Koty potrafią rozpoznać różnice w zapachach i często wykazują zainteresowanie nowymi zapachami.',
	'Koty są bardziej aktywne w nocy niż w ciągu dnia.',
	'Koty są w stanie przejść przez szczeliny, które wydają się zbyt małe dla nich.',
	'Koty są jednymi z najbardziej niezależnych zwierząt domowych.',
	'Koty potrafią rozpoznać emocje swojego właściciela i reagować na nie.',
	'Koty potrafią się kuć i gryźć jako forma zabawy.',
	'Koty mogą być znakomitymi myśliwymi i często polują na gryzonie i ptaki.',
	'Koty potrafią przeskakiwać wysokości, które zdają się zbyt duże dla ich rozmiaru.',
	'Koty są znane z tego, że są wybredne w jedzeniu.',
	'Koty mogą mieć wyjątkowe osobowości, a niektóre są bardziej towarzyskie niż inne.',
	'Koty potrafią zdrapywać korytarze i ścieżki na swoim terytorium.',
	'Koty potrafią być wybredne w wyborze miejsca na spanie i czasem zmieniają miejsca.',
	'Koty nie potrzebują dużo ruchu fizycznego i są zadowolone z życia w zamkniętych pomieszczeniach.',
	'Koty potrafią robić wiele skomplikowanych trików, takich jak psy.',
	'Koty potrafią mieć wyjątkowe osobowości, a niektóre są bardziej towarzyskie niż inne.',
	'Koty mogą być wychowane w różnych kolorach sierści, takie jak czarny, biały, rude i inne.',
	'Koty potrafią rozpoznać innych koty po zapachu.',
	'Koty potrafią komunikować się ze sobą za pomocą mruczenia i miauczenia.',
	'Koty potrafią rozpoznać różnice w tonie głosu i emocjach w głosie swojego właściciela.',
	'Koty potrafią rozpoznać emocje swojego właściciela i reagować na nie.',
	'Koty potrafią rozpoznać różnice w zapachach i często wykazują zainteresowanie nowymi zapachami.',
	'Koty potrafią być bardzo ciekawe i lubią badać nowe rzeczy w otoczeniu.',
	'Koty potrafią rozpoznać głos swojego właściciela.',
	'Koty potrafią komunikować się z innymi kotami za pomocą znaków zapachowych.',
	'Koty potrafią być wrażliwe na zmiany nastroju swojego właściciela.',
	'Koty potrafią być znakomitymi myśliwymi i polują na owady.',
	'Koty potrafią być czułe na zmiany w harmonii domu i reagować na nie.',
	'Koty mają krótki okres ciąży i rodzą małe kocięta.',
	'Koty potrafią przewidywać niektóre rodzaje katastrof, takie jak trzęsienia ziemi.',
	'Koty potrafią odczuwać ból i choroby, ale często ukrywają swoje cierpienie.',
	'Koty potrafią być znakomitymi myśliwymi, ale nie polują z zabijczą intencją.',
	'Koty mają naturalną zdolność do skakania i łapania swoich ofiar.',
	'Koty mogą być wychowywane w różnych kolorach sierści, takie jak czarny, biały, rude i inne.',
	'Koty potrafią rozpoznać innych koty po zapachu.',
	'Koty potrafią komunikować się ze sobą za pomocą mruczenia i miauczenia.',
	'Koty potrafią rozpoznać różnice w tonie głosu i emocjach w głosie swojego właściciela.',
	'Koty potrafią rozpoznać emocje swojego właściciela i reagować na nie.',
	'Koty potrafią rozpoznać różnice w zapachach i często wykazują zainteresowanie nowymi zapachami.',
	'Koty potrafią być bardzo ciekawe i lubią badać nowe rzeczy w otoczeniu.',
	'Koty potrafią rozpoznać głos swojego właściciela.',
	'Koty potrafią komunikować się z innymi kotami za pomocą znaków zapachowych.',
	'Koty potrafią być wrażliwe na zmiany nastroju swojego właściciela.',
	'Koty potrafią być znakomitymi myśliwymi i polują na owady.',
	'Koty potrafią być czułe na zmiany w harmonii domu i reagować na nie.',
	'Koty mają wrodzoną zdolność do skakania i łapania swoich ofiar.',
	'Koty mogą być wychowywane w różnych kolorach sierści, takie jak czarny, biały, rude i inne.',
	'Koty potrafią rozpoznać innych koty po zapachu.',
	'Koty potrafią komunikować się ze sobą za pomocą mruczenia i miauczenia.',
	'Koty potrafią rozpoznać różnice w tonie głosu i emocjach w głosie swojego właściciela.',
	'Koty potrafią rozpoznać emocje swojego właściciela i reagować na nie.',
	'Koty potrafią rozpoznać różnice w zapachach i często wykazują zainteresowanie nowymi zapachami.',
	'Koty potrafią być bardzo ciekawe i lubią badać nowe rzeczy w otoczeniu.',
	'Koty potrafią rozpoznać głos swojego właściciela.',
	'Koty potrafią komunikować się z innymi kotami za pomocą znaków zapachowych.',
	'Koty potrafią być wrażliwe na zmiany nastroju swojego właściciela.',
	'Koty potrafią zdrapywać korytarze i ścieżki na swoim terytorium.',
	'Koty potrafią być wybredne w wyborze miejsca na spanie i czasem zmieniają miejsca.',
	'Koty nie potrzebują dużo ruchu fizycznego i są zadowolone z życia w zamkniętych pomieszczeniach.',
	'Koty potrafią robić wiele skomplikowanych trików, takie jak psy.',
	'Koty potrafią mieć wyjątkowe osobowości, a niektóre są bardziej towarzyskie niż inne.',
	'Koty mogą być wychowane w różnych kolorach sierści, takie jak czarny, biały, rude i inne.',
	'Koty potrafią rozpoznać innych koty po zapachu.',
	'Koty potrafią komunikować się ze sobą za pomocą mruczenia i miauczenia.',
	'Koty potrafią rozpoznać różnice w tonie głosu i emocjach w głosie swojego właściciela.',
	'Koty potrafią rozpoznać emocje swojego właściciela i reagować na nie.',
	'Koty potrafią rozpoznać różnice w zapachach i często wykazują zainteresowanie nowymi zapachami.',
	'Koty potrafią być bardzo ciekawe i lubią badać nowe rzeczy w otoczeniu.',
	'Koty potrafią rozpoznać głos swojego właściciela.',
	'Koty potrafią komunikować się z innymi kotami za pomocą znaków zapachowych.',
	'Koty potrafią być wrażliwe na zmiany nastroju swojego właściciela.',
	'Koty potrafią być znakomitymi myśliwymi i polują na owady.',
	'Koty potrafią być czułe na zmiany w harmonii domu i reagować na nie.',
	'Koty mają krótki okres ciąży i rodzą małe kocięta.',
	'Koty potrafią przewidywać niektóre rodzaje katastrof, takie jak trzęsienia ziemi.',
	'Koty potrafią odczuwać ból i choroby, ale często ukrywają swoje cierpienie.',
	'Koty potrafią być znakomitymi myśliwymi, ale nie polują z zabijczą intencją.',
	'Koty mają naturalną zdolność do skakania i łapania swoich ofiar.',
	'Koty mogą być wychowane w różnych kolorach sierści, takie jak czarny, biały, rude i inne.',
	'Koty potrafią rozpoznać innych koty po zapachu.',
	'Koty potrafią komunikować się ze sobą za pomocą mruczenia i miauczenia.',
	'Koty potrafią rozpoznać różnice w tonie głosu i emocjach w głosie swojego właściciela.',
	'Koty potrafią rozpoznać emocje swojego właściciela i reagować na nie.',
	'Koty potrafią rozpoznać różnice w zapachach i często wykazują zainteresowanie nowymi zapachami.',
	'Koty potrafią być bardzo ciekawe i lubią badać nowe rzeczy w otoczeniu.',
	'Koty potrafią rozpoznać głos swojego właściciela.',
	'Koty potrafią komunikować się z innymi kotami za pomocą znaków zapachowych.',
	'Koty potrafią być wrażliwe na zmiany nastroju swojego właściciela.',
	'Koty potrafią być znakomitymi myśliwymi i polują na owady.',
	'Koty potrafią być czułe na zmiany w harmonii domu i reagować na nie.',
	'Koty mają wrodzoną zdolność do skakania i łapania swoich ofiar.',
	'Koty mogą być wychowane w różnych kolorach sierści, takie jak czarny, biały, rude i inne.',
	'Koty potrafią rozpoznać innych koty po zapachu.',
	'Koty potrafią komunikować się ze sobą za pomocą mruczenia i miauczenia.',
	'Koty potrafią rozpoznać różnice w tonie głosu i emocjach w głosie swojego właściciela.',
	'Koty potrafią rozpoznać emocje swojego właściciela i reagować na nie.',
	'Koty potrafią rozpoznać różnice w zapachach i często wykazują zainteresowanie nowymi zapachami.',
	'Koty potrafią być bardzo ciekawe i lubią badać nowe rzeczy w otoczeniu.',
	'Koty potrafią rozpoznać głos swojego właściciela.',
	'Koty potrafią komunikować się z innymi kotami za pomocą znaków zapachowych.',
	'Koty potrafią być wrażliwe na zmiany nastroju swojego właściciela.',
]

const quiz = [
	{
		question: 'Koty to ssaki.',
		answer: true,
	},
	{
		question: 'Koty są ptakami.',
		answer: false,
	},
	{
		question: 'Koty mają ogon.',
		answer: true,
	},
	{
		question: 'Koty nie potrafią lizać się.',
		answer: false,
	},
	{
		question: 'Koty są mięsożerne.',
		answer: true,
	},
	{
		question: 'Koty są drapieżnikami.',
		answer: true,
	},
	{
		question: 'Koty mogą lizać się, aby się oczyścić.',
		answer: true,
	},
	{
		question: 'Koty zazwyczaj mają futro.',
		answer: true,
	},
	{
		question: 'Koty zawsze lubią pływać.',
		answer: false,
	},
	{
		question: 'Koty często mruczą.',
		answer: true,
	},
	{
		question: 'Koty to psy.',
		answer: false,
	},
	{
		question: 'Koty są roślinożerne.',
		answer: false,
	},
	{
		question: 'Koty są zwierzętami stadnymi.',
		answer: false,
	},
	{
		question: 'Koty nie widzą w ciemności.',
		answer: false,
	},
	{
		question: 'Koty to gady.',
		answer: false,
	},
	{
		question: 'Koty to ryby.',
		answer: false,
	},
	{
		question: 'Koty potrafią skakać wysoko.',
		answer: true,
	},
	{
		question: 'Koty są bardzo leniwe.',
		answer: true,
	},
	{
		question: 'Koty potrafią otwierać drzwi.',
		answer: true,
	},
	{
		question: 'Koty to inteligentne zwierzęta.',
		answer: true,
	},
	{
		question: 'Koty potrafią mówić.',
		answer: false,
	},
	{
		question: 'Koty są niewrażliwe na wodę.',
		answer: false,
	},
	{
		question: 'Koty to zwierzęta socjalne.',
		answer: true,
	},
	{
		question: 'Koty lubią być głaskane.',
		answer: true,
	},
	{
		question: 'Koty to niebezpieczne zwierzęta.',
		answer: false,
	},
	{
		question: 'Koty lubią spać na słońcu.',
		answer: true,
	},
	{
		question: 'Koty są bardzo szybkie.',
		answer: true,
	},
	{
		question: 'Koty są niewrażliwe na zimno.',
		answer: false,
	},
	{
		question: 'Koty potrafią otwierać lodówki.',
		answer: true,
	},
	{
		question: 'Koty to zwierzęta nocne.',
		answer: true,
	},
	{
		question: 'Koty to kotowate.',
		answer: true,
	},
	{
		question: 'Koty są udomowione od tysięcy lat.',
		answer: true,
	},
	{
		question: 'Koty były czczone w starożytnym Egipcie.',
		answer: true,
	},
	{
		question: 'Koty potrafią skakać na znaczną wysokość.',
		answer: true,
	},
	{
		question: 'Koty mają ostra krew.',
		answer: false,
	},
	{
		question: 'Koty mają sześć palców na każdej nodze.',
		answer: false,
	},
	{
		question: 'Koty zazwyczaj mają 9 życia.',
		answer: false,
	},
	{
		question: 'Koty mogą mieć różne długości futra.',
		answer: true,
	},
	{
		question: 'Koty lubią zabawki.',
		answer: true,
	},
	{
		question: 'Koty są jednymi z najpopularniejszych zwierząt domowych na świecie.',
		answer: true,
	},
	{
		question: 'Koty potrafią chodzić na smyczy.',
		answer: false,
	},
	{
		question: 'Koty są bardzo czyste zwierzęta.',
		answer: true,
	},
	{
		question: 'Koty potrafią komunikować się za pomocą mruczenia.',
		answer: true,
	},
	{
		question: 'Koty lubią jeść owoce.',
		answer: false,
	},
	{
		question: 'Koty są zazdrosne o innych kotów.',
		answer: true,
	},
	{
		question: 'Koty potrafią rozwiązywać łamigłówki.',
		answer: true,
	},
	{
		question: 'Koty są wrażliwe na dźwięki.',
		answer: true,
	},
	{
		question: 'Koty są niewrażliwe na promieniowanie słoneczne.',
		answer: false,
	},
	{
		question: 'Koty są w stanie rozpoznać swojego właściciela.',
		answer: true,
	},
	{
		question: 'Koty mają ostre pazury.',
		answer: true,
	},
	{
		question: 'Koty to jedne z niewielu zwierząt, które mrugają do ludzi.',
		answer: true,
	},
	{
		question: 'Koty są niewrażliwe na elektryczność statyczną.',
		answer: false,
	},
	{
		question: 'Koty lubią drapać meble.',
		answer: true,
	},
	{
		question: 'Koty potrafią polować na gryzonie.',
		answer: true,
	},
	{
		question: 'Koty są przeważnie leworęczne.',
		answer: false,
	},
	{
		question: 'Koty mają doskonały słuch.',
		answer: true,
	},
	{
		question: 'Koty nie lubią deszczu.',
		answer: true,
	},
	{
		question: 'Koty są zręczne.',
		answer: true,
	},
	{
		question: 'Koty nie potrafią pływać.',
		answer: true,
	},
	{
		question: 'Koty są w stanie rozpoznać ludzi po zapachu.',
		answer: true,
	},
	{
		question: 'Koty potrafią lizać się w trudno dostępnych miejscach.',
		answer: true,
	},
	{
		question: 'Koty potrafią śpiewać.',
		answer: false,
	},
	{
		question: 'Koty lubią spać w pudełkach.',
		answer: true,
	},
	{
		question: 'Koty mają wyjątkowe zdolności kuropatw.',
		answer: false,
	},
	{
		question: 'Koty potrafią wydawać dźwięki podobne do psiego szczekania.',
		answer: true,
	},
	{
		question: 'Koty potrafią rozpoznać swoje zdjęcie.',
		answer: true,
	},
]



module.exports = {
	funfacts,
	quiz,
}
